### ISSUE TITLE
add option to include max permissible gap duration in the episode duration

### ISSUE THREAD

**Issue by alexadima** [ddediu/AdhereR#146]
In the current version, the compute.treatment.episodes function excludes the maximum.permissible.gap from the episode.duration. If the time gap between the end of the current supply and the next supply is longer than the maximum.permissible.gap, the episode ends when the current supply finishes and the full gap is considered as a treatment interruption or discontinuation. There is also the option of including the maximum.permissible.gap duration in the episode duration - in this case, the episode would end at (end supply date + maximum permissible gap duration). This would be good to be implemented as an additional parameter (add.max.permissible.gap.to.episode with TRUE as default). This addition would address current limitations of different calculation at the end of observation window (recorded in end.episode.gap.days, which is now either number of days after episode end, or number of days within episode after the last supply finished if < than max permissible gap). The current implementation would remain available in the package, as it is commonly used in the literature.

**Comment by ddediu** [comment]
Suggested solution: make it even more general, by allowing the addition of a *percent* of the MAX.PERMISSIBLE.GAP at the end of the episodes with a gap > MAX.PERMISSIBLE.GAP (0% is what happens now, 100% is the original suggestion, but one can imagine in-betweens)

**Comment by ddediu** [comment]
Done!
