### ISSUE TITLE
CMA0 plot timeline does not change if followup.window.duration value changes

### ISSUE THREAD

**Issue by alexadima** [ddediu/AdhereR#15]
cma0 <- CMA0(data=med.events, # use the two selected patients
             ID.colname="PATIENT_ID", # the name of the column containing the IDs
             event.date.colname="DATE", # the name of the column containing the event date
             event.duration.colname="DURATION", # the name of the column containing the duration
             event.daily.dose.colname="PERDAY", # the name of the column containing the dosage
             medication.class.colname="CATEGORY", # the name of the column containing the category
             followup.window.start=0,  # FUW start in days since earliest event
             followup.window.duration=4*365, # OW duration in days
             observation.window.start=0, # OW start in days since earliest event
             observation.window.duration=4*365, # OW duration in days
             date.format="%m/%d/%Y"); # date format (dd/mm/yyyy)
plot(cma0)

irrespective of the value for follow up duration, I think it pick the first date and the last date across patients, and plots all the timeline inbetween

other CMA plots and the CMA interactive work fine

**Comment by ddediu** [comment]
After discussions, this is a new scenario left for the next release.
What we decided was:
- if given, the follow-up window simply cuts the displayed stuff (acts as a very simple viewport); otherwise the viewport is the whole dataset
- if given, the observation window is shown as a yellow rectangle (or something like that); otherwise nothing special is done

**Comment by ddediu** [comment]
Fixed: now plotting CMA0 and CMA1+ use the same conventions (and share quite a bit of code -- refactoring needed???)
