### ISSUE TITLE
warning when unused argument is given

### ISSUE THREAD

**Issue by Masswear** [ddediu/AdhereR#17]
When an argument such as carryover.within.obs.window is passed to CMA-functions that don't use this argument or override it, a warning should be given.

```
example_data <- med.events[med.events$PATIENT_ID %in% c(37, 76), ]

cma1 <- CMA1(data=example_data,
             ID.colname="PATIENT_ID",
             event.date.colname="DATE", 
             event.duration.colname="DURATION", 
             event.daily.dose.colname="PERDAY", 
             medication.class.colname="CATEGORY", #argument not used with CMA1!
             followup.window.start=0,  
             observation.window.start=182, 
             observation.window.duration=365, 
             date.format="%m/%d/%Y",
             carryover.within.obs.window = TRUE) #argument is overridden for each CMA constructor! 
```

**Comment by ddediu** [comment]
I am not entirely sure about this, because it would probably mean, in the extreme, that we should fire a warning for any not explicitly defined argument (I use ... for various reasons, including interactive plotting)...
On the other hand, we could define a specific list of arguments and CMAs that would generate such a warning: what do you think?

**Comment by Masswear** [comment]
Yes, for specific arguments would be sufficient. I opened this issue because I got confused when using the same arguments for two different CMA methods and the results didn't behave as expected. Only after some time I realized that the CMA method in question didn't use one of the arguments provided. So it's essentially the opposite of firing a warning for a not explicitly defined argument. It's more like the "unused argument" error when providing an argument that is not used by the function.

**Comment by ddediu** [comment]
Ok: then maybe the three of us can build a list of such arguments for each CMA?

**Comment by ddediu** [comment]
Good: I implemented the frame work for this, but I need the list of arguments that for each CMAx should generate the warning -- Alex, Sam, would you want to provide it for me pls?

**Comment by ddediu** [comment]
So, a warning is shown for:
CMA1-CMA4: carryover.within.obs.window, carryover.into.obs.window, carry.only.for.same.medication, consider.dosage.change
CMA5-CMA9: carryover.within.obs.window, carryover.into.obs.window
