### ISSUE TITLE
Show carryover in sliding windows and per episode plots ?

### ISSUE THREAD

**Issue by ddediu** [ddediu/AdhereR#172]
Investigate if it is desirable to show the carry over boxes also in the per episode and sliding window plots (as they are in the simple CMA plots). 
Possibly provide a parameter to explicitly force them to be shown (by default `FALSE` to keep the current behavior of not showing them)?

**Comment by ddediu** [comment]
Seems to require a pretty massive restructuring of the way sliding windows and per episodes are computed, as the necessary info is simply not stored right now, so the potting function does not have the info...

**Comment by ddediu** [comment]
... on a second thought, I *think* there might be a way of recovering that info using some data.table tricks :) let me see...

**Comment by dffyfe** [comment]
I can send tomorrow, if you make process.patient return a list then do data[, process.patient(.SD)$listitem1, by=Id.colname] then run it for the CMA and event.info. The event info will be there for each window I.D but using I. In data.table to get max gives you the original

7 Nov 2021 22:13:02 Dan Dediu ***@***.***>:

**Comment by ddediu** [comment]
ok. I was thinking about making it return all the info and then subset it to extract the event.info columns -- I dont know which is faster, might need some benchmarking

**Comment by dffyfe** [comment]
I was getting a weird data.table error saying I could only return a list or atomic vector using by= when I tried that, even though I was literally trying to return a list.

7 Nov 2021 22:23:04 Dan Dediu ***@***.***>:

**Comment by ddediu** [comment]
I did it in a different way: I am merging the two in a single data.table, return it, and then subset them again outside -- seems to work pretty well :)

**Comment by ddediu** [comment]
ok, works and it adds a bit of overhead but it's acceptable (by default it is disabled so it has to be requested explicitly for plotting). It seems I might have a working solution, ow it's just to find time to implement it :)

**Comment by dffyfe** [comment]
Hi Dan,

I think I've got committing to GitHub slightly figured out (and got around
working on a networked computer). Definitely easier than using 7zip every
time!

I've put it here for now as I'm still getting my head round it and don't
want to mess anything up.

dffyfe/AdhereRFork: Fork of AdhereR to be used in STU/MAVIS project
(github.com) <https://github.com/dffyfe/AdhereRFork>

Best,

David

**Comment by ddediu** [comment]
Should be fixed in `devel`
