### ISSUE TITLE
Show legend box outside of the plot area.

### ISSUE THREAD

**Issue by mumbarkar** [ddediu/AdhereR#195]
I am trying to visualize patients medication history over a period of 3 years and when I used entire FUW duration I was not able to see some treatment patterns behind the legend box.

Could you please help me out to plot legend box outside of the plot area?

Thanks in advance.

Mahesh.

**Comment by mumbarkar** [comment]
I got the solution for this one.

thanks.

**Comment by ddediu** [comment]
Dear Mahesh,
indeed, the solution you found is the intended solution for this case: this is why I implemented the `do.not.draw.plot` parameter starting with v0.8.0. However, I am not sure what the best way to publish your solution would be -- maybe best if you yourself do it as a small script?
Best wishes,
Dan
