### ISSUE TITLE
Check !is.na() for the required parameters in compute_event_durations() and time_to_initiation()

### ISSUE THREAD

**Issue by ddediu** [ddediu/AdhereR#21]
Now, it is unclear which of the parameters in these functions are required *not* to be `NA`; for example, in `compute_event_durations()` it is not checked if `!is.na(medication.class.colnames)` (only if it isn't, and if it is included in the column names), which means that passing `medication.class.colname=NA` results in an ugly crash:

```
Error in `[.data.table`(disp.data, get(ID.colname) == pat, c(ID.colname,  : 
  column(s) not found: NA
```

**Comment by ddediu** [comment]
+ if  possible, also add a few unit tests for these cases?
+ make it clearer in the manual which of these parameters *must* be defined?
Thanks,
Dan

**Comment by Masswear** [comment]
I removed the default `NA`s for all required arguments in the function call definition, and also removed them from the manual. This way, someone would have to explicitely define one of these parameters as `NA`, which imho justifies an ugly crash ;).
