### ISSUE TITLE
Plotting issue with plot.cma0 when input data is a data.table 

### ISSUE THREAD

**Issue by Masswear** [ddediu/AdhereR#5]
Trying to plot a cma0 object created from a data.table generates the following error:

> Error in unclass(e1) + unclass(e2) : 
  non-numeric argument to binary operator

Reproducible example:

```
library(AdhereR)
library(data.table)

cma0 <- CMA0(data=as.data.table(med.events), # data.table
             ID.colname="PATIENT_ID",
             event.date.colname="DATE",
             event.duration.colname="DURATION",
             event.daily.dose.colname="PERDAY",
             medication.class.colname="CATEGORY",
             followup.window.start=0,
             followup.window.start.unit="days",
             followup.window.duration=2*365,
             followup.window.duration.unit="days",
             observation.window.start=30,
             observation.window.start.unit="days",
             observation.window.duration=365,
             observation.window.duration.unit="days",
             date.format="%m/%d/%Y",
             summary="Base CMA")
plot(cma0)
```

**Comment by ddediu** [comment]
Interesting bug: it boiled down to a difference in behavior between `data.frame`'s and `data.table`'s for calls of type `d[,x]` where `x` contains a column name (see also data.table [FAQ 1.5](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-faq.html#i-assigned-a-variable-mycol-x-but-then-dt-mycol-returns-x.-how-do-i-get-it-to-look-up-the-column-name-contained-in-the-mycol-variable)). 
Now, if I detect that the `x` argument to the `plot.CMA0` function has a `data.table` as `data` member, I force its downcast to `data.frame` to avoid these inconsistencies...
