### ISSUE TITLE
Fully graphical Shiny wrapper?

### ISSUE THREAD

**Issue by ddediu** [ddediu/AdhereR#52]
no params needed, but it would allow the user the possibility to select everything it needs (data source, column names...) entirely from the Shiny GUI...

**Comment by Masswear** [comment]
Would be useful to have in two tabs (or items in a navbar): first tab to select data & columns, second tab for interactive plotting. Another useful possiblilty would be to export the calculated CMA values.

For the settings sidebar in interactive plotting, collapsible elements would be useful, as provided by the [`bsplus` package](https://github.com/ijlyttle/bsplus). Example for another solution with native JavaScript could be done similar to this: https://stackoverflow.com/questions/49852818/collapsible-menu-item-in-shiny-dashboard-sidebar

**Comment by ddediu** [comment]
+ enable/disable UI elements depending on having dose and treatment class columns defined or not
+ if function called with no params, force user to select dataset

**Comment by ddediu** [comment]
+ enable/disable UI elements depending on having dose and treatment class columns defined or not
+ if function called with no params, force user to select dataset

**Comment by ddediu** [comment]
Seems to work even when launched without arguments (but serious testing is needed)

**Comment by ddediu** [comment]
Seems to pretty much work, but this the first cut really in need of testing, feedback and probably better design...

**Comment by ddediu** [comment]
Pretty much done!
