### ISSUE TITLE
Shiny plotting: explore if main sections in the right panel can be collapsed

### ISSUE THREAD

**Issue by ddediu** [ddediu/AdhereR#58]

**Comment by Masswear** [comment]
Collapsible elements provided by [`bsplus` package](https://github.com/ijlyttle/bsplus). Example for a solution with native JavaScript: https://stackoverflow.com/questions/49852818/collapsible-menu-item-in-shiny-dashboard-sidebar

**Comment by ddediu** [comment]
I ended up using a very simple solution building on `shinyjs`'s `hidden()` and `toggle()` functions...
