### ISSUE TITLE
Group events per medication class in plotting

### ISSUE THREAD

**Issue by Masswear** [ddediu/AdhereR#68]
Currently, plotting is sorted by date. This is useful for single treatment scenarios. For multiple medications, users should have the option to sort plotting by medication class to visually group events of the same medication class together.

**Comment by ddediu** [comment]
Hi Sam,
I'm finally restarting working on this and I don't remember if you implemented these or not?
Would you have time for a skype one of these days?
Dan

**Comment by ddediu** [comment]
I think this covered now pretty much by the medication groups, given that one can even define medication groups that map 1:1 to medication classes...
