### ISSUE TITLE
Idea: Support to donation to help with code maintenance and new features 

### ISSUE THREAD

**Issue by gustavorps** [ddediu/AdhereR#91]
Some suggestions of platforms to manage donations:

- https://opencollective.com/
- https://liberapay.com/
- https://gratipay.com/
- https://www.bountysource.com/
- https://foundation.travis-ci.org/grants/
- https://www.patreon.com/

**Comment by ddediu** [comment]
Does not seem to be a viable option for now... Maybe later, if need be?
